### ISSUE TITLE
Redundant code in testing

### ISSUE THREAD

**Issue by vladimirkovacevic** [mitap94/exact-string-matching#2]
Last 4 cells in unit_testing.ipynb can be replaced with for loop choice 1:4

**Comment by mitap94** [comment]
Group SortedIndex and HashTable in one cell and SuffixArray and SuffixTree in another, because of query differences.

**Comment by mitap94** [comment]
Grouped all query tests in one for loop

**Comment by vladimirkovacevic** [comment]
Thanks :1st_place_medal: 
Older programmers thought me a time ago: In software nothing is impossible. Just a matter of time and money.
